import { Router, Request, Response, NextFunction } from 'express';
import { existsSync } from 'fs';
import { resolve } from 'path';
import { pathToFileURL } from 'url';
import { uploadMiddleware } from '../middleware/upload.js';
import { AppError } from '../middleware/errorHandler.js';
import { generateScanId } from '../utils/scanId.js';
import { cloneRepo, ValidationError, TimeoutError, CloneError } from '../utils/cloneRepo.js';
import { extractZip, ExtractionError } from '../utils/extractZip.js';
import { saveScanResult, getScanResult, saveReport, getReportPath, listRecentScans, cleanupScanFolder, deleteScan, NotFoundError, StorageError } from '../utils/storage.js';
import { scanRateLimiter } from '../middleware/rateLimiter.js';
import { incrementTotalScans, incrementActiveScans, decrementActiveScans } from '../utils/metrics.js';

const router = Router();
const SCAN_TIMEOUT_MS = parseInt(process.env.SCAN_TIMEOUT_MS || '90000', 10);

const resolveRepoModule = (relativePath: string): string => {
  const candidates = [
    resolve(process.cwd(), relativePath),
    resolve(process.cwd(), '..', relativePath),
  ];
  const modulePath = candidates.find(candidate => existsSync(candidate));

  if (!modulePath) {
    throw new Error(`Module not found: ${relativePath}`);
  }

  return pathToFileURL(modulePath).href;
};

// Import scan orchestrator
let runFullScan: (repoPath: string, scanId: string) => Promise<any>;

// Dynamic import to handle CommonJS/ESM compatibility
(async () => {
  try {
    const orchestratorPath = resolveRepoModule('middleware/scanOrchestrator.js');
    const orchestrator = await import(orchestratorPath);
    runFullScan = orchestrator.runFullScan;
    console.log('✓ Scan orchestrator loaded successfully');
  } catch (error) {
    console.warn('⚠ Failed to load scan orchestrator, using mock:', error);
    // Fallback mock function
    runFullScan = async (_repoPath: string, scanId: string) => {
      return {
        scanId,
        status: 'completed',
        timestamp: new Date().toISOString(),
        repoMetadata: {
          name: 'example-repo',
          languages: ['JavaScript', 'TypeScript'],
          frameworks: ['React', 'Express'],
          hasDocker: true,
          hasTests: true,
          fileCount: 50,
          totalLines: 2500,
        },
        readme: {
          title: 'Example Repository',
          content: '# Example Repository\n\nThis is a placeholder README.',
        },
        vulnerabilities: [],
        bugs: [],
        suggestedFixes: [],
        warnings: ['Using mock scan - orchestrator not available'],
      };
    };
  }
})();

// Import report generator
let generateFinalReport: (scanResult: any) => Promise<any> | any;

(async () => {
  try {
    const reportGeneratorPath = resolveRepoModule('agents/reportGeneratorAgent.js');
    const reportGen = await import(reportGeneratorPath);
    generateFinalReport = reportGen.generateFinalReport;
    console.log('✓ Report generator loaded successfully');
  } catch (error) {
    console.warn('⚠ Failed to load report generator, using fallback:', error);
    // Fallback report generator
    generateFinalReport = (scanResult: any) => {
      return `# RepoPilot Scan Report

**Scan ID:** ${scanResult.scanId}
**Timestamp:** ${scanResult.timestamp}
**Status:** ${scanResult.status}

## Repository Metadata
- **Name:** ${scanResult.repoMetadata?.name || 'Unknown'}
- **Languages:** ${scanResult.repoMetadata?.languages?.join(', ') || 'Unknown'}
- **Frameworks:** ${scanResult.repoMetadata?.frameworks?.join(', ') || 'None detected'}
- **File Count:** ${scanResult.repoMetadata?.fileCount || 0}
- **Total Lines:** ${scanResult.repoMetadata?.totalLines || 0}

## Vulnerabilities
Found ${scanResult.vulnerabilities?.length || 0} vulnerabilities.

## Bugs
Found ${scanResult.bugs?.length || 0} bugs.

## Warnings
${scanResult.warnings?.length > 0 ? scanResult.warnings.map((w: string) => `- ${w}`).join('\n') : 'None'}

---
*Generated by RepoPilot*
`;
    };
  }
})();

// Timeout wrapper
const withTimeout = <T>(promise: Promise<T>, timeoutMs: number, operation: string): Promise<T> => {
  let timeoutId: NodeJS.Timeout;
  const timeoutPromise = new Promise<T>((_, reject) => {
    timeoutId = setTimeout(() => reject(new Error(`${operation} timeout after ${timeoutMs}ms`)), timeoutMs);
  });

  return Promise.race([promise, timeoutPromise]).finally(() => {
    clearTimeout(timeoutId!);
  });
};

// POST /api/scan - Start a new scan (with rate limiting)
router.post('/', scanRateLimiter, uploadMiddleware.single('file'), async (req: Request, res: Response, next: NextFunction) => {
  let scanId: string | undefined;
  let repoPath: string | undefined;
  
  try {
    const { type, repoUrl } = req.body;
    scanId = generateScanId();
    
    // Track metrics
    incrementTotalScans();
    incrementActiveScans();

    // Validate request
    if (!type || (type !== 'github' && type !== 'zip')) {
      throw new AppError('Invalid scan type. Must be "github" or "zip"', 400);
    }

    if (type === 'github') {
      if (!repoUrl) {
        throw new AppError('Repository URL is required for GitHub scans', 400);
      }

      console.log(`[${scanId}] Cloning repository: ${repoUrl}`);
      try {
        repoPath = await cloneRepo(repoUrl, scanId);
      } catch (error) {
        // Map custom clone errors to appropriate HTTP status codes
        if (error instanceof ValidationError) {
          throw new AppError(error.message, 400);
        }
        if (error instanceof TimeoutError) {
          throw new AppError(error.message, 408);
        }
        if (error instanceof CloneError) {
          if (error.message.includes('not found')) {
            throw new AppError(error.message, 404);
          }
          throw new AppError(error.message, 500);
        }
        throw error;
      }
    } else {
      if (!req.file) {
        throw new AppError('ZIP file is required for ZIP scans', 400);
      }

      console.log(`[${scanId}] Extracting ZIP file: ${req.file.originalname}`);
      try {
        repoPath = await extractZip(req.file.path, scanId);
      } catch (error) {
        // Map custom extraction errors to appropriate HTTP status codes
        if (error instanceof ExtractionError) {
          throw new AppError(error.message, 400);
        }
        throw error;
      }
    }

    console.log(`[${scanId}] Starting full scan with ${SCAN_TIMEOUT_MS}ms timeout...`);
    
    // Run the scan with timeout
    let scanResult;
    try {
      scanResult = await withTimeout(
        runFullScan(repoPath, scanId),
        SCAN_TIMEOUT_MS,
        'Full scan'
      );
    } catch (timeoutError) {
      if (timeoutError instanceof Error && timeoutError.message.includes('timeout')) {
        console.error(`[${scanId}] Scan timeout exceeded`);
        await cleanupScanFolder(scanId);
        throw new AppError('Scan timeout - repository too large or complex', 503);
      }
      throw timeoutError;
    }

    // Generate report markdown if the orchestrator did not attach it
    console.log(`[${scanId}] Generating report...`);
    let reportMarkdown = scanResult.reportMarkdown;
    if (!reportMarkdown) {
      const reportResult = await generateFinalReport(scanResult);
      reportMarkdown = typeof reportResult === 'string' ? reportResult : reportResult.markdown;
      scanResult = {
        ...scanResult,
        reportMarkdown,
      };
    }

    // Save results and report
    await saveScanResult(scanId, scanResult);
    await saveReport(scanId, reportMarkdown);

    console.log(`[${scanId}] Scan completed successfully`);
    
    // Decrement active scans counter
    decrementActiveScans();

    res.json(scanResult);
  } catch (error) {
    // Decrement active scans counter on error
    decrementActiveScans();
    
    // Cleanup on error
    if (scanId) {
      console.log(`[${scanId}] Error occurred, cleaning up...`);
      try {
        await cleanupScanFolder(scanId);
      } catch (cleanupError) {
        console.error(`[${scanId}] Cleanup failed:`, cleanupError);
      }
    }
    next(error);
  }
});

// GET /api/scan/:scanId - Get scan results
router.get('/:scanId', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { scanId } = req.params;

    if (!scanId || !scanId.startsWith('scan_')) {
      throw new AppError('Invalid scan ID', 400);
    }

    const result = await getScanResult(scanId);
    res.json(result);
  } catch (error) {
    if (error instanceof NotFoundError) {
      next(new AppError(error.message, 404));
    } else if (error instanceof StorageError) {
      next(new AppError(error.message, 500));
    } else {
      next(error);
    }
  }
});

// GET /api/scan/:scanId/report - Download scan report
router.get('/:scanId/report', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { scanId } = req.params;

    if (!scanId || !scanId.startsWith('scan_')) {
      throw new AppError('Invalid scan ID', 400);
    }

    const reportPath = getReportPath(scanId);
    
    res.download(reportPath, `repopilot_${scanId}_report.md`, (err) => {
      if (err) {
        next(new AppError('Failed to download report', 500));
      }
    });
  } catch (error) {
    if (error instanceof NotFoundError) {
      next(new AppError(error.message, 404));
    } else {
      next(error);
    }
  }
});

// GET /api/scans - List recent scans
router.get('/', async (_req: Request, res: Response, next: NextFunction) => {
  try {
    const scans = await listRecentScans(10);
    res.json(scans);
  } catch (error) {
    next(error);
  }
});

// DELETE /api/scan/:scanId - Delete a scan
router.delete('/:scanId', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { scanId } = req.params;
    
    if (!scanId) {
      throw new AppError('Scan ID is required', 400);
    }
    
    await deleteScan(scanId);
    
    // Return 204 No Content on successful deletion
    res.status(204).send();
  } catch (error) {
    if (error instanceof NotFoundError) {
      next(new AppError(error.message, 404));
    } else if (error instanceof StorageError) {
      next(new AppError(error.message, 500));
    } else {
      next(error);
    }
  }
});

export default router;

// Made with Bob
