const formatFix = (fix) => {
  if (typeof fix === 'string') {
    return fix;
  }

  const title = fix?.title || 'Suggested fix';
  const description = fix?.description ? ` - ${fix.description}` : '';
  const file = fix?.file ? ` (${fix.file})` : '';
  return `${title}${file}${description}`;
};

const escapeTableCell = (value) => {
  return String(value ?? '')
    .replace(/\|/g, '\\|')
    .replace(/\r?\n/g, ' ');
};

export const formatFinalReport = (scanResult) => {
  const {
    scanId,
    repoMetadata = {},
    readme = {},
    vulnerabilities = [],
    bugs = [],
    suggestedFixes = [],
    warnings = [],
    timestamp,
  } = scanResult;

  const languages = repoMetadata.languages || [];
  const frameworks = repoMetadata.frameworks || [];
  const fileCount = repoMetadata.fileCount || 0;
  const totalLines = repoMetadata.totalLines || 0;

  const severityEmoji = {
    CRITICAL: '[CRITICAL]',
    HIGH: '[HIGH]',
    MEDIUM: '[MEDIUM]',
    LOW: '[LOW]',
    INFO: '[INFO]',
  };

  let markdown = `# RepoPilot Security & Code Quality Report\n\n`;
  markdown += `**Scan ID:** \`${scanId}\`  \n`;
  markdown += `**Generated:** ${timestamp ? new Date(timestamp).toLocaleString() : new Date().toLocaleString()}  \n`;
  markdown += `**Repository:** ${repoMetadata.name || 'Unknown'}\n\n`;

  markdown += `---\n\n`;

  markdown += `## Executive Summary\n\n`;
  markdown += `| Metric | Count |\n`;
  markdown += `|--------|-------|\n`;
  markdown += `| Vulnerabilities | ${vulnerabilities.length} |\n`;
  markdown += `| Bugs | ${bugs.length} |\n`;
  markdown += `| Suggested Fixes | ${suggestedFixes.length} |\n`;
  markdown += `| Warnings | ${warnings.length} |\n`;
  markdown += `| Files | ${fileCount} |\n`;
  markdown += `| Lines of Code | ${totalLines.toLocaleString()} |\n\n`;

  markdown += `## Repository Metadata\n\n`;
  markdown += `**Languages:** ${languages.join(', ') || 'Unknown'}  \n`;
  markdown += `**Frameworks:** ${frameworks.join(', ') || 'None detected'}  \n`;
  markdown += `**Docker:** ${repoMetadata.hasDocker ? 'Yes' : 'No'}  \n`;
  markdown += `**Tests:** ${repoMetadata.hasTests ? 'Yes' : 'No'}  \n\n`;

  if (warnings.length > 0) {
    markdown += `## Warnings\n\n`;
    warnings.forEach(warning => {
      markdown += `- ${warning}\n`;
    });
    markdown += `\n`;
  }

  markdown += `## Security Vulnerabilities (${vulnerabilities.length})\n\n`;
  if (vulnerabilities.length === 0) {
    markdown += `No vulnerabilities detected.\n\n`;
  } else {
    markdown += `| Severity | Tool | File | Issue | Recommendation |\n`;
    markdown += `|----------|------|------|-------|----------------|\n`;
    vulnerabilities.forEach(vuln => {
      const severity = vuln.severity || 'INFO';
      markdown += `| ${severityEmoji[severity] || severity} | ${escapeTableCell(vuln.tool)} | \`${escapeTableCell(vuln.file)}\` | ${escapeTableCell(vuln.issue)} | ${escapeTableCell(vuln.recommendation)} |\n`;
    });
    markdown += `\n`;
  }

  markdown += `## Code Quality Issues (${bugs.length})\n\n`;
  if (bugs.length === 0) {
    markdown += `No code quality issues detected.\n\n`;
  } else {
    markdown += `| Severity | Tool | File | Issue | Recommendation |\n`;
    markdown += `|----------|------|------|-------|----------------|\n`;
    bugs.forEach(bug => {
      const severity = bug.severity || 'INFO';
      markdown += `| ${severityEmoji[severity] || severity} | ${escapeTableCell(bug.tool)} | \`${escapeTableCell(bug.file)}\` | ${escapeTableCell(bug.issue)} | ${escapeTableCell(bug.recommendation)} |\n`;
    });
    markdown += `\n`;
  }

  markdown += `## Suggested Fixes\n\n`;
  if (suggestedFixes.length === 0) {
    markdown += `No fixes needed.\n\n`;
  } else {
    suggestedFixes.forEach((fix, index) => {
      markdown += `${index + 1}. ${formatFix(fix)}\n`;
    });
    markdown += `\n`;
  }

  markdown += `## Auto-Generated README\n\n`;
  markdown += `${readme.content || ''}\n\n`;

  markdown += `---\n\n`;
  markdown += `*Report generated by RepoPilot - AI-Powered Repository Analysis*  \n`;
  markdown += `*Scan ID: ${scanId}*\n`;

  return markdown;
};

// Made with Bob
