import { readFile } from 'fs/promises';
import { join } from 'path';
import { existsSync } from 'fs';

export const generateReadme = async (repoPath, repoMetadata) => {
  const { name, languages, frameworks, hasDocker, hasTests } = repoMetadata;

  let content = `# ${name}\n\n`;
  
  content += `## Overview\n\n`;
  content += `This repository contains a ${languages.join(', ')} project`;
  if (frameworks.length > 0) {
    content += ` using ${frameworks.join(', ')}`;
  }
  content += `.\n\n`;

  // Tech Stack
  content += `## Tech Stack\n\n`;
  content += `**Languages:** ${languages.join(', ')}  \n`;
  if (frameworks.length > 0) {
    content += `**Frameworks:** ${frameworks.join(', ')}  \n`;
  }
  content += `**Containerization:** ${hasDocker ? '✅ Docker' : '❌ No Docker'}  \n`;
  content += `**Testing:** ${hasTests ? '✅ Tests included' : '❌ No tests detected'}  \n\n`;

  // Installation
  content += `## Installation\n\n`;
  
  // Check for package.json
  const packageJsonPath = join(repoPath, 'package.json');
  if (existsSync(packageJsonPath)) {
    try {
      const pkgContent = await readFile(packageJsonPath, 'utf-8');
      const pkg = JSON.parse(pkgContent);
      
      content += `### Node.js Setup\n\n`;
      content += `\`\`\`bash\n`;
      content += `npm install\n`;
      content += `\`\`\`\n\n`;

      if (pkg.scripts) {
        content += `### Available Scripts\n\n`;
        Object.entries(pkg.scripts).forEach(([script, command]) => {
          content += `- \`npm run ${script}\` - ${command}\n`;
        });
        content += `\n`;
      }
    } catch {
      // Ignore errors
    }
  }

  // Check for requirements.txt
  const requirementsPath = join(repoPath, 'requirements.txt');
  if (existsSync(requirementsPath)) {
    content += `### Python Setup\n\n`;
    content += `\`\`\`bash\n`;
    content += `pip install -r requirements.txt\n`;
    content += `\`\`\`\n\n`;
  }

  // Docker instructions
  if (hasDocker) {
    content += `## Docker\n\n`;
    content += `\`\`\`bash\n`;
    if (existsSync(join(repoPath, 'docker-compose.yml'))) {
      content += `docker compose up -d\n`;
    } else {
      content += `docker build -t ${name} .\n`;
      content += `docker run -p 3000:3000 ${name}\n`;
    }
    content += `\`\`\`\n\n`;
  }

  // Usage
  content += `## Usage\n\n`;
  content += `Please refer to the project documentation for detailed usage instructions.\n\n`;

  // Testing
  if (hasTests) {
    content += `## Testing\n\n`;
    content += `\`\`\`bash\n`;
    if (existsSync(packageJsonPath)) {
      content += `npm test\n`;
    } else if (existsSync(requirementsPath)) {
      content += `pytest\n`;
    }
    content += `\`\`\`\n\n`;
  }

  // Environment Variables
  const envExamplePath = join(repoPath, '.env.example');
  if (existsSync(envExamplePath)) {
    content += `## Environment Variables\n\n`;
    content += `Copy \`.env.example\` to \`.env\` and configure the required variables:\n\n`;
    content += `\`\`\`bash\n`;
    content += `cp .env.example .env\n`;
    content += `\`\`\`\n\n`;
  }

  // Contributing
  content += `## Contributing\n\n`;
  content += `Contributions are welcome! Please feel free to submit a Pull Request.\n\n`;

  // License
  content += `## License\n\n`;
  const licensePath = join(repoPath, 'LICENSE');
  if (existsSync(licensePath)) {
    content += `This project is licensed under the terms specified in the LICENSE file.\n\n`;
  } else {
    content += `Please check with the repository owner for licensing information.\n\n`;
  }

  // Footer
  content += `---\n\n`;
  content += `*This README was auto-generated by RepoPilot*\n`;

  return {
    title: name,
    content,
  };
};

// Made with Bob
